// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-OMZ_wTZmPIsaHeoPWeu5W-ClfFTH3GU',
    appId: '1:321026721925:web:54663193d56fdaf3f401ec',
    messagingSenderId: '321026721925',
    projectId: 'chatapp-7e4f2',
    authDomain: 'chatapp-7e4f2.firebaseapp.com',
    storageBucket: 'chatapp-7e4f2.appspot.com',
    measurementId: 'G-ML7WVNV3T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAN0_ZaijXRUAmc9pA3zM02TuNgjpe6s8',
    appId: '1:321026721925:android:046b0f67a8a0351ef401ec',
    messagingSenderId: '321026721925',
    projectId: 'chatapp-7e4f2',
    storageBucket: 'chatapp-7e4f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6A00Ka7B0mDWyS1p6OUkjzfPsZRlX0lk',
    appId: '1:321026721925:ios:a3396cd782f84986f401ec',
    messagingSenderId: '321026721925',
    projectId: 'chatapp-7e4f2',
    storageBucket: 'chatapp-7e4f2.appspot.com',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6A00Ka7B0mDWyS1p6OUkjzfPsZRlX0lk',
    appId: '1:321026721925:ios:a3396cd782f84986f401ec',
    messagingSenderId: '321026721925',
    projectId: 'chatapp-7e4f2',
    storageBucket: 'chatapp-7e4f2.appspot.com',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-OMZ_wTZmPIsaHeoPWeu5W-ClfFTH3GU',
    appId: '1:321026721925:web:542546d2d94a5a90f401ec',
    messagingSenderId: '321026721925',
    projectId: 'chatapp-7e4f2',
    authDomain: 'chatapp-7e4f2.firebaseapp.com',
    storageBucket: 'chatapp-7e4f2.appspot.com',
    measurementId: 'G-HW00DTMFHZ',
  );
}
